if(EXISTS "/home/leonard/work/hft-engine/build-bin/truetest_cli_tests[1]_tests.cmake")
  include("/home/leonard/work/hft-engine/build-bin/truetest_cli_tests[1]_tests.cmake")
else()
  add_test(truetest_cli_tests_NOT_BUILT truetest_cli_tests_NOT_BUILT)
endif()
